# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'advanced_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(330, 140)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dialog.sizePolicy().hasHeightForWidth())
        dialog.setSizePolicy(sizePolicy)
        dialog.setMinimumSize(QtCore.QSize(330, 140))
        dialog.setMaximumSize(QtCore.QSize(330, 140))
        self.advancedGroupBox = QtWidgets.QGroupBox(dialog)
        self.advancedGroupBox.setEnabled(True)
        self.advancedGroupBox.setGeometry(QtCore.QRect(10, 40, 301, 91))
        self.advancedGroupBox.setObjectName("advancedGroupBox")
        self.bgProgramCloseButton = QtWidgets.QPushButton(self.advancedGroupBox)
        self.bgProgramCloseButton.setGeometry(QtCore.QRect(150, 20, 61, 21))
        self.bgProgramCloseButton.setObjectName("bgProgramCloseButton")
        self.bgProgramStartButton = QtWidgets.QPushButton(self.advancedGroupBox)
        self.bgProgramStartButton.setGeometry(QtCore.QRect(210, 20, 61, 21))
        self.bgProgramStartButton.setObjectName("bgProgramStartButton")
        self.bgProgramStatusLabel = QtWidgets.QLabel(self.advancedGroupBox)
        self.bgProgramStatusLabel.setGeometry(QtCore.QRect(30, 20, 111, 21))
        self.bgProgramStatusLabel.setObjectName("bgProgramStatusLabel")
        self.settingsFileStatusLabel = QtWidgets.QLabel(self.advancedGroupBox)
        self.settingsFileStatusLabel.setGeometry(QtCore.QRect(30, 40, 71, 21))
        self.settingsFileStatusLabel.setObjectName("settingsFileStatusLabel")
        self.settingsFileCreateButton = QtWidgets.QPushButton(self.advancedGroupBox)
        self.settingsFileCreateButton.setGeometry(QtCore.QRect(150, 40, 61, 21))
        self.settingsFileCreateButton.setObjectName("settingsFileCreateButton")
        self.settingsFileDeleteButton = QtWidgets.QPushButton(self.advancedGroupBox)
        self.settingsFileDeleteButton.setGeometry(QtCore.QRect(210, 40, 61, 21))
        self.settingsFileDeleteButton.setObjectName("settingsFileDeleteButton")
        self.startupLabel = QtWidgets.QLabel(self.advancedGroupBox)
        self.startupLabel.setGeometry(QtCore.QRect(30, 60, 101, 21))
        self.startupLabel.setObjectName("startupLabel")
        self.startupDisableButton = QtWidgets.QPushButton(self.advancedGroupBox)
        self.startupDisableButton.setGeometry(QtCore.QRect(210, 60, 61, 21))
        self.startupDisableButton.setObjectName("startupDisableButton")
        self.startupEnableButton = QtWidgets.QPushButton(self.advancedGroupBox)
        self.startupEnableButton.setGeometry(QtCore.QRect(150, 60, 61, 21))
        self.startupEnableButton.setObjectName("startupEnableButton")
        self.loginButton = QtWidgets.QPushButton(dialog)
        self.loginButton.setGeometry(QtCore.QRect(270, 10, 51, 21))
        self.loginButton.setObjectName("loginButton")
        self.pwLabel = QtWidgets.QLabel(dialog)
        self.pwLabel.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.pwLabel.setObjectName("pwLabel")
        self.pwTextBox = QtWidgets.QLineEdit(dialog)
        self.pwTextBox.setGeometry(QtCore.QRect(170, 10, 91, 21))
        self.pwTextBox.setText("")
        self.pwTextBox.setEchoMode(QtWidgets.QLineEdit.Password)
        self.pwTextBox.setObjectName("pwTextBox")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "고급 설정"))
        self.advancedGroupBox.setTitle(_translate("dialog", "고급 설정"))
        self.bgProgramCloseButton.setText(_translate("dialog", "수동종료"))
        self.bgProgramStartButton.setText(_translate("dialog", "수동시작"))
        self.bgProgramStatusLabel.setText(_translate("dialog", "상주프로세스"))
        self.settingsFileStatusLabel.setText(_translate("dialog", "설정파일"))
        self.settingsFileCreateButton.setText(_translate("dialog", "수동생성"))
        self.settingsFileDeleteButton.setText(_translate("dialog", "수동삭제"))
        self.startupLabel.setText(_translate("dialog", "시작프로그램등록"))
        self.startupDisableButton.setText(_translate("dialog", "등록해제"))
        self.startupEnableButton.setText(_translate("dialog", "등록"))
        self.loginButton.setText(_translate("dialog", "로그인"))
        self.pwLabel.setText(_translate("dialog", "고급 설정 활성화 비밀번호:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dialog = QtWidgets.QDialog()
    ui = Ui_dialog()
    ui.setupUi(dialog)
    dialog.show()
    sys.exit(app.exec_())
